### ISSUE TITLE
Build native assets failed

### ISSUE THREAD

**Issue by Predidit** [lindeer/opencc-dart#1]
感谢作者提供了这个优雅的实现。

我在尝试替换已有项目中的FFI调用为这个包时，遇到了本地资源构建失败的问题。

我使用如下命令构建本地资源。

`dart --enable-experiment=native-assets run opencc`

opencc包版本为 1.0.1 , 错误堆栈如下

```
Unhandled exception:
ProcessException: 系统找不到指定的文件。


  Command: which cmake
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      _checkCmd (file:///C:/Users/Predidit/AppData/Local/Pub/Cache/hosted/pub.dev/opencc-1.0.1/build.dart:21:30)
#3      _builder (file:///C:/Users/Predidit/AppData/Local/Pub/Cache/hosted/pub.dev/opencc-1.0.1/build.dart:32:3)
#4      build (package:native_assets_cli/src/api/build.dart:94:16)
#5      main (file:///C:/Users/Predidit/AppData/Local/Pub/Cache/hosted/pub.dev/opencc-1.0.1/build.dart:17:9)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
Building native assets for package:opencc failed.
build.dart returned with exit code: 255.
```

**Comment by lindeer** [comment]
>   Command: which cmake

@Predidit  系统没装cmake 或者 cmake没在环境变量 PATH中

native-asset需要编译安装，系统依赖cmake和make工具

**Comment by Predidit** [comment]
我提交了一个PR #2 

似乎能解决这个问题

**Comment by lindeer** [comment]
@Predidit 已合并，感谢提交
